# Generated by Django 3.0.5 on 2020-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200501_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='blog_desciption',
            field=models.TextField(max_length=500),
        ),
    ]
